
version: '3.8'
services:
  backend:
    build: ./backend
    container_name: quote_backend
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: quote_nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

